### ISSUE TITLE
Missing "config/database.sample.yml"

### ISSUE THREAD

**Issue by kodbilenadam** [telegram-bot-rb/rails_template#2]
I am getting this error due to missing config/database.sample.yml file. Can you update with a existing database sample file? Thanks for now.
```
== Installing dependencies ==
The Gemfile's dependencies are satisfied

== Copying sample files ==
config/database.sample.yml: not found
config/secrets.sample.yml: OK
```

**Comment by printercu** [comment]
Thank you for reporting. Make it copying `database.yml` to `database.sample.yml`, and add it to gitignore.

However with `--skip-active-record` there is message `cp: config/database.yml: No such file or directory`. I hope it's ok. In this case `config/database.sample.yml: not found` will still be present, I'll add note to readme how to avoid it.
