### ISSUE TITLE
Question about the controller

### ISSUE THREAD

**Issue by edencoded** [telegram-bot-rb/rails_template#5]
As this app is, when a message is sent to the bot, a message should be sent back to the chat '.hi', correct?

I'm just trying to understand the code for the TelegramWebhooksController 
```
def start(*)
    respond_with :message, text: t('.hi')
  end
````
Thanks in advance!

**Comment by printercu** [comment]
Hi! This is correct. To see how it works you can take a look at:

- https://github.com/telegram-bot-rb/telegram-bot#controller
- https://github.com/telegram-bot-rb/telegram-bot/blob/master/lib/telegram/bot/updates_controller/reply_helpers.rb

Note that `#start` is invoked for `/start` command but not for any message, how to handle any message is shown in first link. You can read more about commands in Telegram Bots docs.

**Comment by edencoded** [comment]
Oh, thanks for pointing me in the right direction, I gave it another try and everything worked correctly. 

Also want to let you know the `bin/rake telegram:bot:set_webhook RAILS_ENV=production
` step is missing on the production section of this Readme.
